apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    service: app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: ${APP_NODE_PORT}
      targetPort: 80
      protocol: TCP
  selector:
    service: app
