apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa
rules:
  - apiGroups:
      - ''
      - apps
    resources:
      - persistentvolumeclaims
      - configmaps
      - statefulsets
      - deployments
      - replicasets
      - daemonsets
      - pods
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
